name: 'Lint code'
description: Github action to run linter

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - shell: bash
      run: |
        yarn install
        yarn lint