name: 'Interaction Test'
description: Github action to run interaction test

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - shell: bash
      run: |
        npx playwright install-deps
        yarn install
        yarn storybook:test:ci