name: Release-it

on:
  workflow_dispatch:

jobs:
  release-it:
    name: Release-it ✨
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: ./.github/actions/release-it
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
